# Generated by Django 5.1.7 on 2025-03-15 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TextImageRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text_content", models.TextField(verbose_name="文本内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("image_width", models.IntegerField(default=1200, verbose_name="图片宽度")),
                (
                    "image_height",
                    models.IntegerField(default=1500, verbose_name="图片高度"),
                ),
                ("font_size", models.IntegerField(default=36, verbose_name="字体大小")),
                ("line_spacing", models.FloatField(default=2.0, verbose_name="行间距")),
                (
                    "background_style",
                    models.CharField(
                        default="notebook", max_length=20, verbose_name="背景样式"
                    ),
                ),
                (
                    "font_style",
                    models.CharField(
                        default="normal", max_length=20, verbose_name="字体样式"
                    ),
                ),
            ],
            options={
                "verbose_name": "文本图片请求",
                "verbose_name_plural": "文本图片请求",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        upload_to="text_images/%Y/%m/%d/", verbose_name="图片文件"
                    ),
                ),
                ("page_number", models.IntegerField(default=0, verbose_name="页码")),
                (
                    "is_long_image",
                    models.BooleanField(default=False, verbose_name="是否为长图"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="text_image.textimagerequest",
                        verbose_name="关联请求",
                    ),
                ),
            ],
            options={
                "verbose_name": "生成图片",
                "verbose_name_plural": "生成图片",
                "ordering": ["request", "page_number"],
            },
        ),
    ]
